let recognition=null,recognizing=false,timerInterval=null,secondsElapsed=0,stream=null;
const $=s=>document.querySelector(s);
function wordCount(s){return(s.trim().match(/\b[\p{L}\p{N}’']+\b/gu)||[]).length;}
function computeWPM(t,s){if(s<=0)return 0;const w=wordCount(t);return Math.round((w/s)*60);}
function percentFromWPM(w){return Math.round(Math.min(100,(w/100)*100));}
function formatTime(s){const m=Math.floor(s/60).toString().padStart(2,'0');const ss=(s%60).toString().padStart(2,'0');return`${m}:${ss}`;}
function startTimer(){secondsElapsed=0;$('#masaRekod').textContent='00:00';timerInterval=setInterval(()=>{secondsElapsed++;$('#masaRekod').textContent=formatTime(secondsElapsed);},1000);}
function stopTimer(){if(timerInterval)clearInterval(timerInterval);timerInterval=null;}
function kiraTP(p){if(p>=90)return 6;if(p>=75)return 5;if(p>=60)return 4;if(p>=45)return 3;if(p>=30)return 2;return 1;}
function tambahRekod(n,k,t,w,p,tp,m){const tb=document.querySelector('#rekodTable tbody');const d=new Date();const tr=document.createElement('tr');tr.innerHTML=`<td>${d.toLocaleDateString()}</td><td>${d.toLocaleTimeString()}</td><td>${n}</td><td>${k}</td><td>${t}</td><td>${w}</td><td>${p}%</td><td>TP${tp}</td><td>${m}</td>`;tb.prepend(tr);}
function startCamera(){navigator.mediaDevices.getUserMedia({video:true,audio:false}).then(s=>{stream=s;const v=$('#videoPreview');v.srcObject=s;v.style.display='block';$('#btnHentiKamera').disabled=false;}).catch(()=>alert('Kamera tidak dapat diakses.'));}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}$('#videoPreview').style.display='none';$('#btnHentiKamera').disabled=true;}
function checkIfNoVoiceDetected(t){return!t||t.trim().length===0;}
function processUploadedAudio(f){const c=new(window.AudioContext||window.webkitAudioContext)();const r=new FileReader();r.onload=e=>{c.decodeAudioData(e.target.result,b=>{const d=b.duration;const wpm=Math.round((80/d)*60);const p=percentFromWPM(wpm);const tp=kiraTP(p);$('#uploadStatus').textContent=`Rakaman dianalisis: WPM ${wpm}, Peratus ${p}%, TP${tp}`;const n=$('#namaMurid').value||'Tanpa Nama';const k=$('#kelasMurid').value||'-';tambahRekod(n,k,Math.round(d),wpm,p,tp,0);});};r.readAsArrayBuffer(f);} 
window.addEventListener('DOMContentLoaded',()=>{const m=$('#btnMula'),t=$('#btnTamat'),up=$('#btnUploadAudio'),fi=$('#audioUpload');if(m)m.addEventListener('click',()=>{startTimer();m.disabled=true;t.disabled=false;});if(t)t.addEventListener('click',()=>{stopTimer();const txt=$('#transkrip').value;if(checkIfNoVoiceDetected(txt)){alert('Rakaman suara tidak dikesan. Sila muat naik rakaman untuk dinilai.');return;}const n=$('#namaMurid').value||'Tanpa Nama';const k=$('#kelasMurid').value||'-';const w=computeWPM(txt,secondsElapsed);const p=percentFromWPM(w);const tp=kiraTP(p);tambahRekod(n,k,secondsElapsed,w,p,tp,0);m.disabled=false;t.disabled=true;});if(up&&fi){up.addEventListener('click',()=>fi.click());fi.addEventListener('change',()=>{const f=fi.files[0];if(f)processUploadedAudio(f);});}$('#btnKamera').onclick=startCamera;$('#btnHentiKamera').onclick=stopCamera;});
